name: Deploy website to GitHub Pages

defaults:
  run:
    working-directory: ./website

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Deploy Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # for some reason i need to clear the parent directory or get a postcss error
      - name: Set up directory structure
        run: |
          cd ..
          shopt -s extglob
          rm -rf !(website)

      - name: Install dependencies
        run: npm ci

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm run deploy
